//loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

// splash
export const SPLASH_SCREEN_WARMING_UP = 'SPLASH_SCREEN_WARMING_UP';
export const SPLASH_SCREEN_READY = 'SPLASH_SCREEN_READY';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILED = 'LOGIN_FAILED';

// pit
export const CONTRACTOR_REQUEST = 'CONTRACTOR_REQUEST';
export const CONTRACTOR_RESPONSE = 'CONTRACTOR_RESPONSE';
export const CONTRACTOR_REQUEST_FAILED = 'CONTRACTOR_REQUEST_FAILED';