export const LOADING_ACTION_SET_START = 'LOADING_ACTION_SET_START'
export const LOADING_ACTION_SET_END = 'LOADING_ACTION_SET_END'

export const INITIALIZE_ACTION_SET_START = 'INITIALIZE_ACTION_SET_START'
export const INITIALIZE_ACTION_SET_END = 'INITIALIZE_ACTION_SET_END'
