export const NETWORK_ACTION_REQUEST = 'NETWORK_ACTION_REQUEST'
export const NETWORK_ACTION_SET_CONNECTION = 'NETWORK_ACTION_SET_CONNECTION'
export const NETWORK_ACTION_SET_ERROR = 'NETWORK_ACTION_SET_ERROR'
