export const TOGGLE_LOADING = 'TOGGLE_LOADING'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'

export const TRENDING_MANGA_FETCH = 'TRENDING_MANGA_FETCH'
export const TRENDING_MANGA_FETCH_SUCCESS = 'TRENDING_MANGA_FETCH_SUCCESS'
